elasticsearch:
  image: ind3x/rpi-elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  environment:
    LS_JAVA_OPTS: "-Xmx128m -Xms128m"
  ports:
    - "9200:9200"
    - "9300:9300"

#logstash:
#  build: logstash/
#  command: logstash -f /etc/logstash/conf.d/logstash.conf
#  volumes:
#    - ./logstash/config:/etc/logstash/conf.d
#  ports:
#    - "5000:5000"
#  links:
#    - elasticsearch

kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  environment:
    LS_JAVA_OPTS: "-Xmx128m -Xms128m"
  ports:
    - "5601:5601"
  links:
    - elasticsearch


